### ISSUE TITLE
ValidationMessage options not working with a keyword list

### ISSUE THREAD

**Issue by benvp** [mirego/absinthe_error_payload#7]
I have an `AbsintheErrorPayload` struct which has been generated by the `build_payload/2` middleware. Anyway, when having keyword list  as the  `options` the resolution breaks with the following error:

```
Request: POST /api/graphiql
** (exit) an exception was raised:
    ** (BadMapError) expected a map, got: {:constraint, :unique}
        (elixir) lib/map.ex:437: Map.get({:constraint, :unique}, :key, nil)
        (absinthe) lib/absinthe/middleware/map_get.ex:9: Absinthe.Middleware.MapGet.call/2
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:209: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:168: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:153: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:72: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:98: Absinthe.Phase.Document.Execution.Resolution.walk_results/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:87: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:257: Absinthe.Phase.Document.Execution.Resolution.build_result/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:153: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:72: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:98: Absinthe.Phase.Document.Execution.Resolution.walk_results/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:87: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:257: Absinthe.Phase.Document.Execution.Resolution.build_result/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:153: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:72: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:257: Absinthe.Phase.Document.Execution.Resolution.build_result/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:153: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:72: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:53: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
```

Here is the struct I used:

```elixir
%AbsintheErrorPayload.Payload{
  messages: [],
  result: [
    %AbsintheErrorPayload.ValidationMessage{
      code: :unique,
      field: "credential.email",
      key: :email,
      message: "has already been taken",
      options: [constraint: :unique, constraint_name: "credentials_email_index"],
      template: "has already been taken"
    }
  ],
  successful: true
}
```

*Edit*: It only breaks if we query for the `options` in the GraphQL query.

**Comment by pwightman** [comment]
I ran into this as well...is fixing this as easy as changing tidy_opts to convert to a map?

https://github.com/mirego/absinthe_error_payload/blob/1590e4ec03587cf4c35d38cbfd3cf7e2daa9d0a3/lib/absinthe_error_payload/changeset_parser.ex#L98-L100

e.g.

```elixir
defp tidy_opts(opts) do
  opts
  |> Keyword.drop([:validation, :max, :is, :min, :code])
  |> Enum.into(%{})
end
```

If so, I'm happy to submit a PR 👍
